const AllProducts = [
  {
    _id: "0",
    name: "Elment Knights",
    price: 28.99,
    rating: 3.9,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/0.jpg",
  },
  {
    _id: "1",
    name: "Gabur Winston",
    price: 129.99,
    rating: 2.0,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/1.jpg",
  },
  {
    _id: "2",
    name: "N90 Oxford",
    price: 18.99,
    rating: 2.8,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/2.jpg",
  },
  {
    _id: "3",
    name: "Gabur Square",
    price: 124.99,
    rating: 2.0,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/3.jpg",
  },
  {
    _id: "4",
    name: "Locaste Court",
    price: 39.99,
    rating: 2.6,
    description: "A golden shoe - How insane is that?!",
    image: "/shoes_imgs/4.jpg",
  },
  {
    _id: "5",
    name: "Locaste T70",
    price: 137.99,
    rating: 4.7,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/5.jpg",
  },
  {
    _id: "6",
    name: "Elment Cogna",
    price: 140.99,
    rating: 5.0,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/6.jpg",
  },
  {
    _id: "7",
    name: "Vens Square",
    price: 54.99,
    rating: 3.0,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/7.jpg",
  },
  {
    _id: "8",
    name: "Croocs Cogna",
    price: 148.99,
    rating: 4.8,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/8.jpg",
  },
  {
    _id: "9",
    name: "Bagutti Skool",
    price: 23.99,
    rating: 2.1,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/9.jpg",
  },
  {
    _id: "10",
    name: "Gabur Cogna",
    price: 55.99,
    rating: 3.6,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/10.jpg",
  },
  {
    _id: "11",
    name: "Locaste Skool",
    price: 12.99,
    rating: 2.7,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/11.jpg",
  },
  {
    _id: "12",
    name: "Croocs Square",
    price: 106.99,
    rating: 2.4,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/12.jpg",
  },
  {
    _id: "13",
    name: "Adidos Oxford",
    price: 109.99,
    rating: 3.6,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/13.jpg",
  },
  {
    _id: "14",
    name: "Bagutti Cogna",
    price: 122.99,
    rating: 3.2,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/14.jpg",
  },
  {
    _id: "15",
    name: "Elment Skool",
    price: 110.99,
    rating: 3.1,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/15.jpg",
  },
  {
    _id: "16",
    name: "Gabur Knights",
    price: 130.99,
    rating: 2.4,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/16.jpg",
  },
  {
    _id: "17",
    name: "Croocs Court",
    price: 108.99,
    rating: 4.7,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/17.jpg",
  },
  {
    _id: "18",
    name: "N90 Cogna",
    price: 57.99,
    rating: 2.7,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/18.jpg",
  },
  {
    _id: "19",
    name: "Locaste Square",
    price: 97.99,
    rating: 4.5,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/19.jpg",
  },
  {
    _id: "20",
    name: "Elment Winston",
    price: 21.99,
    rating: 2.8,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/20.jpg",
  },
  {
    _id: "21",
    name: "Croocs T70",
    price: 95.99,
    rating: 3.3,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/21.jpg",
  },
  {
    _id: "22",
    name: "Elment Knights",
    price: 25.99,
    rating: 4.7,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/22.jpg",
  },
  {
    _id: "23",
    name: "Naike Cogna",
    price: 150.99,
    rating: 4.4,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/23.jpg",
  },
  {
    _id: "24",
    name: "Gabur Cogna",
    price: 77.99,
    rating: 3.2,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/24.jpg",
  },
  {
    _id: "25",
    name: "Adidos Cogna",
    price: 30.99,
    rating: 3.8,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/25.jpg",
  },
  {
    _id: "26",
    name: "Gabur Cogna",
    price: 141.99,
    rating: 3.2,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/26.jpg",
  },
  {
    _id: "27",
    name: "Timmy Trainers",
    price: 37.99,
    rating: 2.0,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/27.jpg",
  },
  {
    _id: "28",
    name: "Timmy Trainers",
    price: 97.99,
    rating: 4.9,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/28.jpg",
  },
  {
    _id: "29",
    name: "Naike Tanjun",
    price: 57.99,
    rating: 4.6,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/29.jpg",
  },
  {
    _id: "30",
    name: "Gabur Square",
    price: 48.99,
    rating: 3.3,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/30.jpg",
  },
  {
    _id: "31",
    name: "Vens Tanjun",
    price: 110.99,
    rating: 3.9,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/31.jpg",
  },
  {
    _id: "32",
    name: "Adidos Square",
    price: 126.99,
    rating: 4.0,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/32.jpg",
  },
  {
    _id: "33",
    name: "Vens T70",
    price: 107.99,
    rating: 4.3,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/33.jpg",
  },
  {
    _id: "34",
    name: "Timmy Skool",
    price: 72.99,
    rating: 4.4,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/34.jpg",
  },
  {
    _id: "35",
    name: "Elment T70",
    price: 95.99,
    rating: 4.6,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/35.jpg",
  },
  {
    _id: "36",
    name: "N90 Trainers",
    price: 53.99,
    rating: 4.5,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/36.jpg",
  },
  {
    _id: "37",
    name: "N90 Cogna",
    price: 43.99,
    rating: 3.2,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/37.jpg",
  },
  {
    _id: "38",
    name: "Adidos Cogna",
    price: 147.99,
    rating: 2.7,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/38.jpg",
  },
  {
    _id: "39",
    name: "Adidos Knights",
    price: 19.99,
    rating: 3.0,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/39.jpg",
  },
  {
    _id: "40",
    name: "Timmy Knights",
    price: 36.99,
    rating: 2.1,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/40.jpg",
  },
  {
    _id: "41",
    name: "Naike Knights",
    price: 44.99,
    rating: 3.0,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/41.jpg",
  },
  {
    _id: "42",
    name: "Gabur Square",
    price: 73.99,
    rating: 3.5,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/42.jpg",
  },
  {
    _id: "43",
    name: "Gabur Cogna",
    price: 149.99,
    rating: 3.5,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/43.jpg",
  },
  {
    _id: "44",
    name: "Locaste Court",
    price: 134.99,
    rating: 2.2,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/44.jpg",
  },
  {
    _id: "45",
    name: "Vens Cogna",
    price: 116.99,
    rating: 2.9,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/45.jpg",
  },
  {
    _id: "46",
    name: "Timmy Cogna",
    price: 25.99,
    rating: 4.7,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/46.jpg",
  },
  {
    _id: "47",
    name: "Bagutti Winston",
    price: 113.99,
    rating: 3.4,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/47.jpg",
  },
  {
    _id: "48",
    name: "Adidos Tanjun",
    price: 55.99,
    rating: 3.1,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/48.jpg",
  },
  {
    _id: "49",
    name: "Locaste Trainers",
    price: 27.99,
    rating: 4.3,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/49.jpg",
  },
  {
    _id: "50",
    name: "Croocs T70",
    price: 74.99,
    rating: 4.5,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/50.jpg",
  },
  {
    _id: "51",
    name: "Croocs Winston",
    price: 88.99,
    rating: 4.5,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/51.jpg",
  },
  {
    _id: "52",
    name: "Gabur Trainers",
    price: 46.99,
    rating: 3.9,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/52.jpg",
  },
  {
    _id: "53",
    name: "Vens Tanjun",
    price: 117.99,
    rating: 2.8,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/53.jpg",
  },
  {
    _id: "54",
    name: "Bagutti Trainers",
    price: 126.99,
    rating: 4.2,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/54.jpg",
  },
  {
    _id: "55",
    name: "Adidos Knights",
    price: 131.99,
    rating: 4.7,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/55.jpg",
  },
  {
    _id: "56",
    name: "Vens Oxford",
    price: 145.99,
    rating: 4.4,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/56.jpg",
  },
  {
    _id: "57",
    name: "Gabur Trainers",
    price: 77.99,
    rating: 2.4,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/57.jpg",
  },
  {
    _id: "58",
    name: "Croocs Trainers",
    price: 125.99,
    rating: 4.2,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/58.jpg",
  },
  {
    _id: "59",
    name: "Bagutti Court",
    price: 78.99,
    rating: 3.7,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/59.jpg",
  },
  {
    _id: "60",
    name: "Adidos Tanjun",
    price: 14.99,
    rating: 2.8,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/60.jpg",
  },
  {
    _id: "61",
    name: "Bagutti Court",
    price: 33.99,
    rating: 2.4,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/61.jpg",
  },
  {
    _id: "62",
    name: "Locaste Knights",
    price: 120.99,
    rating: 3.9,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/62.jpg",
  },
  {
    _id: "63",
    name: "Elment Oxford",
    price: 131.99,
    rating: 4.8,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/63.jpg",
  },
  {
    _id: "64",
    name: "Timmy Trainers",
    price: 41.99,
    rating: 2.4,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/64.jpg",
  },
  {
    _id: "65",
    name: "N90 Trainers",
    price: 24.99,
    rating: 2.6,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/65.jpg",
  },
  {
    _id: "66",
    name: "Timmy Knights",
    price: 13.99,
    rating: 4.2,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/66.jpg",
  },
  {
    _id: "67",
    name: "N90 Court",
    price: 68.99,
    rating: 2.9,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/67.jpg",
  },
  {
    _id: "68",
    name: "Bagutti Cogna",
    price: 11.99,
    rating: 4.4,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/68.jpg",
  },
  {
    _id: "69",
    name: "Bagutti Winston",
    price: 145.99,
    rating: 2.9,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/69.jpg",
  },
  {
    _id: "70",
    name: "Elment Skool",
    price: 56.99,
    rating: 3.8,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/70.jpg",
  },
  {
    _id: "71",
    name: "Timmy Tanjun",
    price: 112.99,
    rating: 2.9,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/71.jpg",
  },
  {
    _id: "72",
    name: "Naike Oxford",
    price: 30.99,
    rating: 4.9,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/72.jpg",
  },
  {
    _id: "73",
    name: "Elment Trainers",
    price: 123.99,
    rating: 2.1,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/73.jpg",
  },
  {
    _id: "74",
    name: "Naike Knights",
    price: 13.99,
    rating: 2.2,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/74.jpg",
  },
  {
    _id: "75",
    name: "Vens Oxford",
    price: 46.99,
    rating: 2.8,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/75.jpg",
  },
  {
    _id: "76",
    name: "Elment Square",
    price: 32.99,
    rating: 3.2,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/76.jpg",
  },
  {
    _id: "77",
    name: "Gabur T70",
    price: 52.99,
    rating: 3.9,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/77.jpg",
  },
  {
    _id: "78",
    name: "Adidos Skool",
    price: 76.99,
    rating: 2.2,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/78.jpg",
  },
  {
    _id: "79",
    name: "Elment Cogna",
    price: 124.99,
    rating: 4.6,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/79.jpg",
  },
  {
    _id: "80",
    name: "Gabur Tanjun",
    price: 120.99,
    rating: 2.7,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/80.jpg",
  },
  {
    _id: "81",
    name: "Bagutti T70",
    price: 50.99,
    rating: 5.0,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/81.jpg",
  },
  {
    _id: "82",
    name: "Naike Skool",
    price: 12.99,
    rating: 4.5,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/82.jpg",
  },
  {
    _id: "83",
    name: "Vens Winston",
    price: 93.99,
    rating: 3.3,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/83.jpg",
  },
  {
    _id: "84",
    name: "Gabur Trainers",
    price: 60.99,
    rating: 2.0,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/84.jpg",
  },
  {
    _id: "85",
    name: "Gabur Winston",
    price: 101.99,
    rating: 3.7,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/85.jpg",
  },
  {
    _id: "86",
    name: "Locaste Knights",
    price: 111.99,
    rating: 2.2,
    description: "Looks nice at every occasion",
    image: "/shoes_imgs/86.jpg",
  },
];

export default AllProducts;
